const SECTIONS = [
  { id: 'personal1', title: 'Personal Information I', fields: [
    { id: 'surname', label: 'Surname (as in passport)' },
    { id: 'givenNames', label: 'Given names' },
    { id: 'fullNameNative', label: 'Full name in native alphabet' },
    { id: 'otherNames', label: 'Used other names?', type: 'radio' },
    { id: 'otherNamesList', label: 'Other names used' },
    { id: 'sex', label: 'Sex', type: 'select', options: { m: 'Male', f: 'Female' } },
    { id: 'maritalStatus', label: 'Marital status', type: 'select', options: { single: 'Single', married: 'Married', divorced: 'Divorced', widowed: 'Widowed', separated: 'Legally separated' } },
    { id: 'dob', label: 'Date of birth' },
    { id: 'pobCity', label: 'City of birth' },
    { id: 'pobCountry', label: 'Country of birth' },
    { id: 'photo', label: 'Photo attached', type: 'file' },
  ]},
  { id: 'personal2', title: 'Personal Information II', fields: [
    { id: 'nationality', label: 'Nationality' },
    { id: 'otherNationality', label: 'Holds another nationality?', type: 'radio' },
    { id: 'otherNationalityCountry', label: 'Other nationality country' },
    { id: 'nationalIdNumber', label: 'National ID number' },
    { id: 'usSSN', label: 'U.S. Social Security Number' },
    { id: 'usTaxId', label: 'U.S. Taxpayer ID Number' },
  ]},
  { id: 'travel', title: 'Travel Information', fields: [
    { id: 'purpose', label: 'Purpose of trip', type: 'select', options: { b1b2: 'Tourism / Business (B1/B2)', f1: 'Student (F1)', j1: 'Exchange visitor (J1)', h: 'Temporary worker (H)', c: 'Transit (C)', other: 'Other' } },
    { id: 'specificPlans', label: 'Has specific travel plans?', type: 'radio' },
    { id: 'arrivalDate', label: 'Intended arrival date' },
    { id: 'lengthOfStay', label: 'Intended length of stay' },
    { id: 'arrivalApprox', label: 'Approximate arrival date' },
    { id: 'usAddress', label: 'Address in the U.S.' },
    { id: 'whoPays', label: 'Who pays for the trip', type: 'select', options: { self: 'Myself', other: 'Another person', employer: 'Employer', otherorg: 'Other organization' } },
  ]},
  { id: 'companions', title: 'Travel Companions', fields: [
    { id: 'travelingWithOthers', label: 'Others traveling with applicant?', type: 'radio' },
    { id: 'companionsList', label: 'Companions (names and relationship)' },
    { id: 'travelingAsGroup', label: 'Traveling as part of a group/organization?', type: 'radio' },
    { id: 'groupName', label: 'Group or organization name' },
  ]},
  { id: 'previousus', title: 'Previous U.S. Travel', fields: [
    { id: 'beenToUS', label: 'Been to the U.S. before?', type: 'radio' },
    { id: 'lastVisitDate', label: 'Date of last visit' },
    { id: 'previousVisaNumber', label: 'Previous visa number' },
    { id: 'usDriverLicense', label: 'Holds/held a U.S. driver\'s license?', type: 'radio' },
    { id: 'usDriverLicenseNumber', label: 'License number' },
    { id: 'usDriverLicenseState', label: 'State that issued it' },
    { id: 'visaRefused', label: 'Ever refused a U.S. visa?', type: 'radio' },
    { id: 'refusedDetails', label: 'Refusal details' },
    { id: 'petitionFiled', label: 'Immigrant petition ever filed?', type: 'radio' },
  ]},
  { id: 'address', title: 'Address & Contact', fields: [
    { id: 'homeAddress', label: 'Home address' },
    { id: 'mailingSame', label: 'Mailing address same as home?', type: 'radio' },
    { id: 'mailingAddress', label: 'Mailing address' },
    { id: 'phone', label: 'Phone number' },
    { id: 'email', label: 'Email address' },
    { id: 'socialMedia', label: 'Social media' },
  ]},
  { id: 'passport', title: 'Passport Information', fields: [
    { id: 'passportType', label: 'Passport type', type: 'select', options: { regular: 'Regular', official: 'Official', diplomatic: 'Diplomatic', other: 'Other' } },
    { id: 'passportNumber', label: 'Passport number' },
    { id: 'passportIssueCountry', label: 'Country that issued passport' },
    { id: 'passportIssueDate', label: 'Issue date' },
    { id: 'passportExpiryDate', label: 'Expiration date' },
    { id: 'passportLost', label: 'Passport ever lost or stolen?', type: 'radio' },
    { id: 'lostDetails', label: 'Loss/theft details' },
    { id: 'passportScan', label: 'Passport scan attached', type: 'file' },
  ]},
  { id: 'uscontact', title: 'U.S. Contact Person', fields: [
    { id: 'contactName', label: 'Contact person or organization' },
    { id: 'contactRelationship', label: 'Relationship to you' },
    { id: 'contactAddress', label: 'Address' },
    { id: 'contactPhone', label: 'Phone number' },
    { id: 'contactEmail', label: 'Email address' },
  ]},
  { id: 'family', title: 'Family Information', fields: [
    { id: 'fatherName', label: "Father's full name" },
    { id: 'fatherDob', label: "Father's date of birth" },
    { id: 'fatherInUS', label: 'Father in the U.S.?', type: 'radio' },
    { id: 'motherName', label: "Mother's full name" },
    { id: 'motherDob', label: "Mother's date of birth" },
    { id: 'motherInUS', label: 'Mother in the U.S.?', type: 'radio' },
    { id: 'spouseName', label: "Spouse's full name" },
    { id: 'otherRelativesUS', label: 'Other relatives in the U.S.?', type: 'radio' },
    { id: 'relativesDetails', label: 'Relatives details' },
  ]},
  { id: 'work', title: 'Work / Education', fields: [
    { id: 'occupation', label: 'Present occupation' },
    { id: 'employerName', label: 'Employer / school name' },
    { id: 'employerAddress', label: 'Employer / school address' },
    { id: 'monthlyIncome', label: 'Monthly income' },
    { id: 'educationLevel', label: 'Highest education level', type: 'select', options: { primary: 'Primary', secondary: 'Secondary', university: 'University', postgraduate: 'Postgraduate' } },
    { id: 'institutionName', label: 'Institution name' },
  ]},
  { id: 'prevworkedu', title: 'Additional Work / Education', fields: [
    { id: 'previousEmployer1Name', label: 'Previous employer name (last 5 years)' },
    { id: 'previousEmployer1JobTitle', label: 'Job title' },
    { id: 'previousEmployer1Dates', label: 'Employment dates' },
    { id: 'languagesSpoken', label: 'Languages spoken' },
    { id: 'traveledLast5Years', label: 'Traveled to other countries in last 5 years?', type: 'radio' },
    { id: 'countriesVisited', label: 'Countries visited' },
    { id: 'professionalOrgMembership', label: 'Belongs to professional/social/civic organizations?', type: 'radio' },
    { id: 'orgDetails', label: 'Organization details' },
    { id: 'specializedSkills', label: 'Specialized skills (firearms, explosives, nuclear, biological, chemical)?', type: 'radio' },
    { id: 'specializedSkillsDetails', label: 'Specialized skills details' },
    { id: 'militaryService', label: 'Ever served in the military?', type: 'radio' },
    { id: 'militaryDetails', label: 'Military service details' },
    { id: 'paramilitaryInvolvement', label: 'Involved with paramilitary/rebel/guerrilla group?', type: 'radio' },
  ]},
  { id: 'security', title: 'Security & Background', fields: [
    { id: 'communicableDisease', label: 'Communicable disease of public health significance?', type: 'radio' },
    { id: 'mentalDisorder', label: 'Mental/physical disorder posing a threat?', type: 'radio' },
    { id: 'drugAbuser', label: 'Drug abuser or addict?', type: 'radio' },
    { id: 'criminalRecord', label: 'Ever arrested or convicted?', type: 'radio' },
    { id: 'drugViolation', label: 'Ever violated controlled-substance laws?', type: 'radio' },
    { id: 'prostitution', label: 'Involved in prostitution/vice in last 10 years?', type: 'radio' },
    { id: 'moneyLaundering', label: 'Involved in money laundering?', type: 'radio' },
    { id: 'humanTrafficking', label: 'Committed or conspired to commit human trafficking?', type: 'radio' },
    { id: 'traffickingBenefit', label: "Benefited from family member's trafficking activities?", type: 'radio' },
    { id: 'espionage', label: 'Sought espionage/sabotage/export violations?', type: 'radio' },
    { id: 'terroristActivity', label: 'Sought to engage in terrorist activities?', type: 'radio' },
    { id: 'terroristSupport', label: 'Provided support to terrorist activities/organizations?', type: 'radio' },
    { id: 'terroristOrgMember', label: 'Member/representative of a terrorist organization?', type: 'radio' },
    { id: 'familyTerroristActivity', label: 'Family member engaged in terrorist activity (last 5 years)?', type: 'radio' },
    { id: 'genocide', label: 'Participated in genocide?', type: 'radio' },
    { id: 'torture', label: 'Participated in torture?', type: 'radio' },
    { id: 'extrajudicialKillings', label: 'Committed extrajudicial/political killings or violence?', type: 'radio' },
    { id: 'childSoldier', label: 'Recruited or used child soldiers?', type: 'radio' },
    { id: 'religiousFreedomViolation', label: 'Severe violations of religious freedom?', type: 'radio' },
    { id: 'forcedPopulationControl', label: 'Involved in coercive population control?', type: 'radio' },
    { id: 'organTransplant', label: 'Involved in coercive organ transplantation?', type: 'radio' },
    { id: 'immigrationViolation', label: 'Ever violated U.S. visa terms?', type: 'radio' },
    { id: 'visaFraud', label: 'Sought visa/entry by fraud or misrepresentation?', type: 'radio' },
    { id: 'removalProceedings', label: 'Failed to attend removal hearing (last 5 years)?', type: 'radio' },
    { id: 'previouslyDeported', label: 'Ever removed/deported from any country?', type: 'radio' },
    { id: 'childCustody', label: 'Withheld custody of a U.S. citizen child?', type: 'radio' },
    { id: 'votingViolation', label: 'Voted in the U.S. in violation of law?', type: 'radio' },
    { id: 'renouncedCitizenship', label: 'Renounced U.S. citizenship to avoid taxation?', type: 'radio' },
  ]},
];

module.exports = { SECTIONS };
