const SECTIONS = [
  { id: "personal1", title: "Personal Information I", fields: [
    { id: "surname", label: "Surname (as in passport)" },
    { id: "givenNames", label: "Given names" },
    { id: "fullNameNative", label: "Full name in native alphabet (if different)" },
    { id: "otherNames", label: "Have you ever used other names?", type: "radio" },
    { id: "otherNamesList", label: "List all other names used" },
    { id: "sex", label: "Sex", type: "select", options: {"m": "Male", "f": "Female"} },
    { id: "maritalStatus", label: "Marital status", type: "select", options: {"single": "Single", "engaged": "Engaged", "married": "Married", "civil": "Civil union / common-law", "divorced": "Divorced", "widowed": "Widowed", "separated": "Legally separated"} },
    { id: "dob", label: "Date of birth", type: "date" },
    { id: "pobCity", label: "City of birth" },
    { id: "pobCountry", label: "Country of birth" },
    { id: "photo", label: "Photo for visa application", type: "file" },
  ]},
  { id: "personal2", title: "Personal Information II", fields: [
    { id: "nationality", label: "Nationality" },
    { id: "otherNationality", label: "Do you hold another nationality?", type: "radio" },
    { id: "otherNationalityCountry", label: "Which country" },
    { id: "hasResidencyOtherCountry", label: "Do you have permanent residency (residence permit) in another country?", type: "radio" },
    { id: "residencyCountry", label: "Which country and status" },
    { id: "nationalIdNumber", label: "National identification number (if any)" },
    { id: "usSSN", label: "U.S. Social Security Number (if any)" },
    { id: "usTaxId", label: "U.S. Taxpayer ID Number (if any)" },
  ]},
  { id: "travel", title: "Travel Information", fields: [
    { id: "purpose", label: "Purpose of trip", type: "select", options: {"b1b2": "Tourism / Business (B1/B2)", "f1": "Student (F1)", "j1": "Exchange visitor (J1)", "h": "Temporary worker (H)", "c": "Transit (C)", "other": "Other"} },
    { id: "specificPlans", label: "Do you have specific travel plans already?", type: "radio" },
    { id: "arrivalDate", label: "Intended date of arrival", type: "date" },
    { id: "lengthOfStay", label: "Intended length of stay" },
    { id: "arrivalApprox", label: "Approximate arrival date" },
    { id: "lengthOfStayApprox", label: "Approximate length of stay" },
    { id: "usAddress", label: "Address where you will stay in the U.S.", type: "textarea" },
    { id: "whoPays", label: "Who is paying for the trip", type: "select", options: {"self": "Myself", "other": "Another person", "employer": "Employer", "otherorg": "Other organization"} },
  ]},
  { id: "companions", title: "Travel Companions", fields: [
    { id: "travelingWithOthers", label: "Is anyone traveling with you — family, friends, colleagues?", type: "radio" },
    { id: "companionsCount", label: "How many people (including you)?" },
    { id: "companionsList", label: "List their names and relationship to you", type: "textarea" },
    { id: "travelingAsGroup", label: "Are you traveling as part of a group or organization (e.g. a tour group)?", type: "radio" },
    { id: "groupName", label: "Group or organization name" },
  ]},
  { id: "previousus", title: "Previous U.S. Travel", fields: [
    { id: "beenToUS", label: "Have you ever been to the U.S.?", type: "radio" },
    { id: "lastVisitDate", label: "Date of last visit", type: "date" },
    { id: "previousVisaNumber", label: "Previous visa number (if known)" },
    { id: "usDriverLicense", label: "Do you hold, or have you ever held, a U.S. driver's license?", type: "radio" },
    { id: "usDriverLicenseNumber", label: "License number" },
    { id: "usDriverLicenseState", label: "State that issued it" },
    { id: "visaRefused", label: "Have you ever been refused a U.S. visa?", type: "radio" },
    { id: "refusedDetails", label: "Please explain", type: "textarea" },
    { id: "petitionFiled", label: "Has anyone ever filed an immigrant petition on your behalf?", type: "radio" },
  ]},
  { id: "address", title: "Address & Contact", fields: [
    { id: "homeAddress", label: "Home address", type: "textarea" },
    { id: "mailingSame", label: "Is your mailing address the same as your home address?", type: "radio" },
    { id: "mailingAddress", label: "Mailing address", type: "textarea" },
    { id: "phone", label: "Phone number", type: "tel" },
    { id: "email", label: "Email address", type: "email" },
    { id: "socialMedia", label: "Social media (platform: username)" },
  ]},
  { id: "passport", title: "Passport Information", fields: [
    { id: "passportType", label: "Type of your international (travel) passport", type: "select", options: {"regular": "Regular", "official": "Official", "diplomatic": "Diplomatic", "other": "Other"} },
    { id: "passportNumber", label: "Passport number" },
    { id: "passportIssueCountry", label: "Country that issued passport" },
    { id: "passportIssueDate", label: "Issue date", type: "date" },
    { id: "passportExpiryDate", label: "Expiration date", type: "date" },
    { id: "passportLost", label: "Has your passport ever been lost or stolen?", type: "radio" },
    { id: "lostDetails", label: "Please explain" },
    { id: "passportScan", label: "Scan of passport data page", type: "file" },
  ]},
  { id: "uscontact", title: "U.S. Contact Person", fields: [
    { id: "contactName", label: "Contact person or organization" },
    { id: "contactRelationship", label: "Relationship to you" },
    { id: "contactAddress", label: "Address", type: "textarea" },
    { id: "contactPhone", label: "Phone number", type: "tel" },
    { id: "contactEmail", label: "Email address", type: "email" },
  ]},
  { id: "family", title: "Family Information", fields: [
    { id: "fatherName", label: "Father's full name" },
    { id: "fatherDob", label: "Father's date of birth", type: "date" },
    { id: "fatherInUS", label: "Is your father in the U.S.?", type: "radio" },
    { id: "fatherStatus", label: "Father's immigration status", type: "select", options: {"citizen": "U.S. citizen", "green_card": "Green card holder", "visa": "On a visa", "other": "Other / unknown"} },
    { id: "motherName", label: "Mother's full name" },
    { id: "motherDob", label: "Mother's date of birth", type: "date" },
    { id: "motherInUS", label: "Is your mother in the U.S.?", type: "radio" },
    { id: "motherStatus", label: "Mother's immigration status", type: "select", options: {"citizen": "U.S. citizen", "green_card": "Green card holder", "visa": "On a visa", "other": "Other / unknown"} },
    { id: "spouseName", label: "Spouse's full name" },
    { id: "otherRelativesUS", label: "Do you have other relatives in the U.S.?", type: "radio" },
    { id: "relativesDetails", label: "Please list them, including their names, relationship, and immigration status (citizen, green card, visa, etc.)", type: "textarea" },
  ]},
  { id: "work", title: "Work / Education", fields: [
    { id: "currentlyEmployed", label: "Are you currently employed or studying?", type: "radio" },
    { id: "occupation", label: "Present occupation (or \"not employed\", \"student\", \"retired\")" },
    { id: "employerName", label: "Employer / school name" },
    { id: "employerAddress", label: "Employer / school address", type: "textarea" },
    { id: "employmentDates", label: "Employed since (from – to, or \"present\")" },
    { id: "monthlyIncome", label: "Monthly income (if employed)" },
    { id: "educationLevel", label: "Highest education level", type: "select", options: {"primary": "Primary", "secondary": "Secondary", "university": "University", "postgraduate": "Postgraduate"} },
    { id: "institutionName", label: "Institution name" },
    { id: "educationDates", label: "Years attended (from – to, or \"present\")" },
  ]},
  { id: "prevworkedu", title: "Additional Work / Education", fields: [
    { id: "previousEmployer1Name", label: "Previous employer name (last 5 years, if any)" },
    { id: "previousEmployer1JobTitle", label: "Job title" },
    { id: "previousEmployer1Dates", label: "Employment dates (from – to)" },
    { id: "languagesSpoken", label: "Languages you speak" },
    { id: "traveledLast5Years", label: "Have you traveled to any other countries in the last five years?", type: "radio" },
    { id: "countriesVisited", label: "Which countries", type: "textarea" },
    { id: "professionalOrgMembership", label: "Do you belong to any professional, social, or civic organizations?", type: "radio" },
    { id: "orgDetails", label: "Please list them", type: "textarea" },
    { id: "specializedSkills", label: "Do you have specialized skills or training in firearms, explosives, nuclear, biological, or chemical fields?", type: "radio" },
    { id: "specializedSkillsDetails", label: "Please explain", type: "textarea" },
    { id: "militaryService", label: "Have you ever served in the military?", type: "radio" },
    { id: "militaryDetails", label: "Country, branch, rank, dates, specialty", type: "textarea" },
    { id: "paramilitaryInvolvement", label: "Have you ever served in or been involved with a paramilitary unit, vigilante unit, rebel group, guerrilla group, or insurgent organization?", type: "radio" },
  ]},
  { id: "security", title: "Security & Background", fields: [
    { id: "h_health", label: "Health", type: "heading" },
    { id: "communicableDisease", label: "Do you have a communicable disease of public health significance?", type: "radio" },
    { id: "mentalDisorder", label: "Do you have a mental or physical disorder that has posed or may pose a threat to yourself or others?", type: "radio" },
    { id: "drugAbuser", label: "Are you or have you ever been a drug abuser or addict?", type: "radio" },
    { id: "h_criminal", label: "Criminal history", type: "heading" },
    { id: "criminalRecord", label: "Have you ever been arrested or convicted of any offense?", type: "radio" },
    { id: "drugViolation", label: "Have you ever violated any law related to controlled substances?", type: "radio" },
    { id: "prostitution", label: "Have you ever been involved in prostitution or vice within the past 10 years?", type: "radio" },
    { id: "moneyLaundering", label: "Have you ever been involved in money laundering?", type: "radio" },
    { id: "humanTrafficking", label: "Have you committed or conspired to commit human trafficking?", type: "radio" },
    { id: "traffickingBenefit", label: "Have you knowingly benefited from a family member's trafficking activities?", type: "radio" },
    { id: "h_security", label: "Security and terrorism", type: "heading" },
    { id: "espionage", label: "Have you sought to engage in espionage, sabotage, export control violations, or other illegal activity in the U.S.?", type: "radio" },
    { id: "terroristActivity", label: "Have you sought to engage in terrorist activities?", type: "radio" },
    { id: "terroristSupport", label: "Have you provided financial assistance or other support to terrorist activities or organizations?", type: "radio" },
    { id: "terroristOrgMember", label: "Are you a member or representative of a terrorist organization?", type: "radio" },
    { id: "familyTerroristActivity", label: "Has a family member engaged in terrorist activity in the last five years?", type: "radio" },
    { id: "genocide", label: "Have you ever ordered, incited, assisted, or otherwise participated in genocide?", type: "radio" },
    { id: "torture", label: "Have you committed, ordered, incited, assisted, or otherwise participated in torture?", type: "radio" },
    { id: "extrajudicialKillings", label: "Have you committed extrajudicial killings, political killings, or other acts of violence?", type: "radio" },
    { id: "childSoldier", label: "Have you recruited or used child soldiers?", type: "radio" },
    { id: "religiousFreedomViolation", label: "Have you engaged in particularly severe violations of religious freedom?", type: "radio" },
    { id: "forcedPopulationControl", label: "Have you been directly involved in coercive population control (forced abortion or sterilization)?", type: "radio" },
    { id: "organTransplant", label: "Have you been involved in the coercive transplantation of human organs or bodily tissue?", type: "radio" },
    { id: "h_immigration", label: "Immigration violations", type: "heading" },
    { id: "immigrationViolation", label: "Have you ever violated the terms of a U.S. visa?", type: "radio" },
    { id: "visaFraud", label: "Have you sought to obtain a visa or enter the U.S. by fraud or misrepresentation?", type: "radio" },
    { id: "removalProceedings", label: "Have you failed to attend a hearing on removal or deportation within the last five years?", type: "radio" },
    { id: "previouslyDeported", label: "Have you ever been removed or deported from any country?", type: "radio" },
    { id: "h_misc", label: "Other", type: "heading" },
    { id: "childCustody", label: "Have you withheld custody of a U.S. citizen child from a person granted legal custody?", type: "radio" },
    { id: "votingViolation", label: "Have you ever voted in the United States in violation of any law or regulation?", type: "radio" },
    { id: "renouncedCitizenship", label: "Have you ever renounced U.S. citizenship to avoid taxation?", type: "radio" },
  ]},
];

module.exports = { SECTIONS };
